// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBFGnksqorM6uW8Q5w3dlnvw20JCQtHgyw',
    appId: '1:237137688914:web:339c2580c4b3ad12f5228b',
    messagingSenderId: '237137688914',
    projectId: 'clinic-3ec85',
    authDomain: 'clinic-3ec85.firebaseapp.com',
    storageBucket: 'clinic-3ec85.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC3dfauKO7PZSDvAseGqGf2EBn9vAKGzqY',
    appId: '1:237137688914:android:9b5a197f84eb36a3f5228b',
    messagingSenderId: '237137688914',
    projectId: 'clinic-3ec85',
    storageBucket: 'clinic-3ec85.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD59xfLzE8EF8cZDyBg9lcvf4EpWLcHtX4',
    appId: '1:237137688914:ios:46d22ebde00644c6f5228b',
    messagingSenderId: '237137688914',
    projectId: 'clinic-3ec85',
    storageBucket: 'clinic-3ec85.appspot.com',
    iosClientId: '237137688914-ba94efct3o493734074bkk0bsljaenbn.apps.googleusercontent.com',
    iosBundleId: 'com.example.clinic',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD59xfLzE8EF8cZDyBg9lcvf4EpWLcHtX4',
    appId: '1:237137688914:ios:46d22ebde00644c6f5228b',
    messagingSenderId: '237137688914',
    projectId: 'clinic-3ec85',
    storageBucket: 'clinic-3ec85.appspot.com',
    iosClientId: '237137688914-ba94efct3o493734074bkk0bsljaenbn.apps.googleusercontent.com',
    iosBundleId: 'com.example.clinic',
  );
}
